FROM golang:1.18.4-alpine3.16 AS build

WORKDIR /app

COPY . .

RUN go mod download

RUN go build ./cmd/reddit/main.go

FROM alpine:3.15.0-rc.4

WORKDIR /app

COPY --from=build /app /app

EXPOSE 8381

ENTRYPOINT [ "./main" ]