apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
      version: v1
  template:
    metadata:
      labels:
        app: auth-server
        version: v1
    spec:
      containers:
        - name: auth-server
          image: mikehsu0618/reddit-auth:latest
          ports:
            - containerPort: 8081
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /app/configs # 使用 configmap 覆盖默认的配置文件
              name: configs
      volumes:
        - name: configs
          configMap:
            name: reddit-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - port: 8081
      targetPort: 8081
      appProtocol: http
      name: http
#  type: LoadBalancer # TODO Test
