reddit:
  server:
    name: "reddit"
    host: "reddit"
    http:
      port: ":8381"
auth:
  server:
    name: 'auth'
    host: 'auth'
    http:
      port: ':8081'
user:
  db:
    host: 'user-db'
    port: '5432'
    user: 'postgres'
    password: 'postgres'
    name: 'user'
  server:
    name: 'user'
    host: 'user'
    http:
      port: ':8181'
post:
  db:
    host: 'post-db'
    port: '5432'
    user: 'postgres'
    password: 'postgres'
    name: 'post'
  server:
    name: 'post'
    host: 'post'
    http:
      port: ':8281'
jwt:
  secret: 'secret'
  expires: 36000