blog:
  server:
    name: "blog"
    host: "blog-server"
    grpc:
      port: ":50050"
    http:
      port: ":8050"
    metrics:
      port: ":9050"
user:
  db:
    host: 'localhost'
    port: '5432'
    user: 'postgres'
    password: 'postgres'
    name: 'user'
  server:
    name: 'user'
    host: 'user-server'
    grpc:
      port: ':50051'
    http:
      port: ':8051'
    metrics:
      port: ':9051'
post:
  db:
    host: 'localhost'
    port: '5433'
    user: 'postgres'
    password: 'postgres'
    name: 'post'
  server:
    name: 'post'
    host: 'post-server'
    grpc:
      port: ':50052'
    http:
      port: ':8052'
    metrics:
      port: ':9052'
comment:
  db:
    host: 'db'
    port: '5432'
    user: 'postgres'
    password: 'postgres'
    name: 'comments'
  server:
    name: 'comment'
    host: 'comment-server'
    grpc:
      port: ':50053'
    http:
      port: ':8053'
    metrics:
      port: ':9053'
auth:
  server:
    name: 'auth'
    host: 'auth-server'
    grpc:
      port: ':50054'
    http:
      port: ':8054'
    metrics:
      port: ':9054'
dtm:
  server:
    name: 'dtm'
    host: 'dtm-server'
    grpc:
      port: ':36790'
    http:
      port: ':36789'
jwt:
  secret: 'secret'
  expires: 36000